name: build_test_benchmark
on: 
  push:
    branches:
      - master

jobs:
  bazel-and-test:
    name: Build-And-Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: print-bazel-version
      run: bazel --version
    - name: install g++11
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 11
    - name: build
      run: bazel build --compilation_mode=opt "..."
    - name: test
      run: bazel test "..." --compilation_mode=opt
    - name: example
      run: bazel run //:example --compilation_mode=opt
    - name: benchmark
      run: ./bazel-bin/bench_mark --benchmark_time_unit=ms
    - name: cppcheck
      uses: deep5050/cppcheck-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        exclude_check: ./test
    - name: publish_report
      uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_NAME: 'master' # your branch name goes here