name: build_test_benchmark
on: 
  push:
    branches:
      - master

jobs:
  bazel-and-test:
    name: Build-And-Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: print-bazel-version
      run: bazel --version
    - name: install g++11
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 11
    - name: build
      run: bazel build --compilation_mode=opt "..."
    - name: test
      run: bazel test "..." --compilation_mode=opt
    - name: example
      run: bazel run //:quick_start --compilation_mode=opt
    - name: benchmark
      run: ./bazel-bin/bench_mark --benchmark_time_unit=ms
    - name: coroutine
      run: bazel run //:benchmark_with_rapidjson --compilation_mode=opt